# Group devRant

## Rants [/devrant/rants{?app,plat,token_id,token_key,user_id,guid,sid,seid,sort,skip}]

+ Parameters

    + app: `3` (number) - The ID of the app which is running the request. As far as tested, only the value 3 works here. Everything else results in the error "Invalid app id specified."
    + plat: `3` (number, optional) - The ID of the platform which the app is running on.
    + token_id: `563363` (number, optional) - The token ID of the user currently logged in.
    + token_key: `mTknUFC$SHpZDB9QhGU8n4NEUFpz!EYERw48Sctj` (string, optional) - The token string of the user currently logged in.
    + user_id: `644182` (number, optional) - The ID of the user currently logged in.
    + guid: `7509943a-7ef0-11e7-bb31-be2e44b06b34` (string, optional) - Current GUID.
    + sid: `1502483704000` (number, optional) - The unix timestamp in milliseconds when the session started.
    + seid: `342` (number, optional) - An event ID that is incremented each request. It starts with 1 and is stored and reused in the next session.
    + sort: `algo` (string, optional) - "algo", "recent" or "top". Specifies the way returned rants will be sorted.
    + skip: `10` (number, optional) - How many rants should be skipped (e.g. for pagination)

### List rants [GET]
Returns a JSON object with 20 rants. The `rants.user_avatar.i`-property defines the path of the user avatar image on the `https://avatars.devrant.io/`-host.

+ Response 200 (application/json)

    + Body

            {
                "success": true,
                "rants": [
                    {
                        "id": 771522,
                        "text": "I started creating a complete API documentation for devRant. What do you guys think?\nIt's far from finished yet, but I'm heavily developing it right now.\nHere's the repository: https:\\/\\/github.com\\/ThePlatzhalter\\/...\nA preview is available at https:\\/\\/htmlpreview.github.io\\/\\/...",
                        "score": 2,
                        "created_time": 1502545536,
                        "attached_image": "",
                        "num_comments": 3,
                        "tags": [
                            "api",
                            "documentation",
                            "devrant"
                        ],
                        "vote_state": 0,
                        "edited": false,
                        "links": [
                            {
                                "type": "url",
                                "url": "https:\\/\\/github.com\\/ThePlatzhalter\\/devRant-API",
                                "short_url": "https:\\/\\/github.com\\/ThePlatzhalter\\/...",
                                "title": "https:\\/\\/github.com\\/ThePlatzhalter\\/...",
                                "start": 177,
                                "end": 214,
                                "special": 1
                            },
                            {
                                "type": "url",
                                "url": "https:\\/\\/htmlpreview.github.io\\/?https:\\/\\/raw.githubusercontent.com\\/ThePlatzhalter\\/devRant-API\\/master\\/dist\\/documentation.html",
                                "short_url": "https:\\/\\/htmlpreview.github.io\\/\\/...",
                                "title": "https:\\/\\/htmlpreview.github.io\\/\\/...",
                                "start": 241,
                                "end": 275,
                                "special": 1
                            }
                        ],
                        "special": true,
                        "user_id": 644182,
                        "user_username": "wildcard",
                        "user_score": 859,
                        "user_avatar": {
                            "b": "7bc8a4",
                            "i": "v-17_c-3_b-1_g-m_9-1_1-3_16-2_3-13_8-1_7-1_5-1_12-3_6-31_2-10_4-1.jpg"
                        }
                    }
                ],
                "settings": [ ],
                "set": "598e4acaa8626"
            }

+ Response 400 (application/json)

    + Body

            {
                "success": false,
                "error": "Invalid app id specified."
            }